//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeABowApi.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakeABowDBEntities : DbContext
    {
        public TakeABowDBEntities()
            : base("name=TakeABowDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<BlockIP> BlockIPs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersBlocked> UsersBlockeds { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
    }
}
