//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeABowApi.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersBlocked
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int BlockedUserId { get; set; }
        public bool IsBlocked { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
